site_name: Salesforce Inspector Advanced
site_url: https://dufoli.github.io/Salesforce-Inspector-reloaded/
repo_url: https://github.com/dufoli/Salesforce-Inspector-reloaded
site_author: Olivier Dufour
theme:
  name: material
  logo: assets/images/icon128.png
  favicon: assets/images/icon128.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dufoli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thomasprouvot/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - CHANGES.md
        - README.md
      check_paths: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/dufoli" target="_blank" rel="noopener">Olivier Dufour</a>
